module.exports = {
  theme: {
    extend: {
      fontWeight: {
        normal: 300,
        medium: 400,
        semibold: 500,
        bold: 700,
        extrabold: 800,
        black: 900,
      },
      colors: {
        zui: {
          dark: "#121212",
          light: "#202020",
          white: "#FFFFFF",
          red: "#FF4545",
          green: "#66DF48",
          yellow: "#FFD600",
          orange: "#FF9E4C",
          purple: "#9803CE",
          blue: "#6A77DD",
          pink: "#FF2F8E",
          neon: "#CFFF50",
          silver: "#5A5A5A",
          lighter: "#161616",
          stroke: "#ffffff1a",
          lightest: "#292929",
        },
        cherry: {
          background: {
            primary: "#F0EDDE",
            input: "#E9E5D3",
            card: "#FFFFFF",
            brown: "#63290D",
            cherry: "#E33056",
            red: "#FF4545",
            lightred: "#FFD8D8",
            green: "#66DF48",
            lightgreen: "#D9FFCF",
            yellow: "#FFD600",
            orange: "#FF9E4C",
            lightorange: "#FFE3CC",
            pink: "#FF2F8E",
            neon: "#CFFF50",
            blue: "#6A77DD",
            purple: "#9803CE",
          },
          stroke: {
            primary: "#E2DFCF",
            secondary: "#C7A08E",
            selected: "#FFFFFF",
            focus: "#63290D",
          },
          text: {
            primary: "#63290D",
            secondary: "#C7A08E",
            buttonprimary: "#F0EDDE",
            buttonsecondary: "#E33056",
            ondarkbg: "#FFFFFF",
            lightgreen: "#D9FFCF",
            lightred: "#FFD8D8",
            lightorange: "#FFE3CC",
          },
          button: {
            primary: "#E33056",
            disabled: "#C7A08E",
          },
          icon: {
            actionable: "#E33056",
            primary: "#63290D",
            light: "#C7A08E",
            background: "#F2E8E4",
            white: "#FFFFFF",
          },
        },
        zostel: {
          light: {
            background: {
              primary: "#FFFFFF",
              secondary: "#F2F2F2",
              input: "rgba(17, 17, 17, 0.1)",
              card: "#FFFFFF",
            },
            stroke: {
              primary: "rgba(17, 17, 17, 0.16)",
              secondary: "rgba(17, 17, 17, 0.44)",
              action: "#111111",
            },
            text: {
              primary: "#111111",
              secondary: "rgba(17, 17, 17, 0.44)",
              inverted: "#FFFFFF",
              action: "#111111",
              hyperlink: "#CFFF50",
            },
            icon: {
              primary: "#111111",
              viewonly: "rgba(17, 17, 17, 0.44)",
            },
          },
          dark: {
            background: {
              primary: "#111111",
              secondary: "#202020",
              input: "rgba(255, 255, 255, 0.1)",
              card: "#111111",
            },
            stroke: {
              primary: "rgba(255, 255, 255, 0.16)",
              secondary: "rgba(255, 255, 255, 0.44)",
              action: "#111111",
            },
            text: {
              primary: "#FFFFFF",
              secondary: "rgba(255, 255, 255, 0.44)",
              inverted: "#111111",
              action: "#FFFFFF",
              hyperlink: "#CFFF50",
            },
            icon: {
              primary: "#111111",
              viewonly: "rgba(255, 255, 255, 0.44)",
            },
          },
          common: {
            success: "#54B835",
            progress: "#FF9E4C",
            error: "#FF4545",
            zostel: "#F1563F",
            "zostel-homes": "#00BEA9",
            "zostel-plus": "#111111",
            yellow: "#FFD600",
            pink: "#FF2F8E",
            purple: "#9803CE",
            blue: "#2C67F6",
          },
        },
      },
      fontSize: {
        xxs: "10px",
      },
      spacing: {
        14: "56px",
        18: "72px",
      },
    },
  },
  plugins: [],
};
