// Parse a free-text "socials" field into a (platform, handle) tuple used to
// build share-slug URLs like /p/<platform>/<handle>.
//
// Platform letters:
//   x = Twitter / X
//   l = LinkedIn
//   g = GitHub
//   i = Instagram
//   y = YouTube
//   u = unparseable (random handle is generated by the caller)

export type SocialPlatform = "x" | "l" | "g" | "i" | "y" | "u";

export interface SocialIdentity {
  platform: SocialPlatform;
  handle: string;
}

const HANDLE_SAFE = /[^a-z0-9-_.]/g;

function sanitizeHandle(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/^@/, "")
    .replace(HANDLE_SAFE, "")
    .slice(0, 64);
}

export function parseSocialIdentity(socials: string): SocialIdentity | null {
  const trimmed = (socials || "").trim();
  if (!trimmed) return null;

  const xMatch = trimmed.match(
    /(?:^|\/\/|\s)(?:x\.com|twitter\.com)\/(@?[A-Za-z0-9_]+)/i
  );
  if (xMatch) {
    const handle = sanitizeHandle(xMatch[1]);
    return handle ? { platform: "x", handle } : null;
  }

  const ghMatch = trimmed.match(/github\.com\/([A-Za-z0-9-_]+)/i);
  if (ghMatch) {
    const handle = sanitizeHandle(ghMatch[1]);
    return handle ? { platform: "g", handle } : null;
  }

  const igMatch = trimmed.match(/instagram\.com\/([A-Za-z0-9-_.]+)/i);
  if (igMatch) {
    const handle = sanitizeHandle(igMatch[1]);
    return handle ? { platform: "i", handle } : null;
  }

  const ytMatch = trimmed.match(
    /youtube\.com\/(?:@|c\/|user\/)?([A-Za-z0-9-_.]+)/i
  );
  if (ytMatch) {
    const handle = sanitizeHandle(ytMatch[1]);
    return handle ? { platform: "y", handle } : null;
  }

  const liMatch = trimmed.match(/linkedin\.com\/in\/([A-Za-z0-9-_]+)/i);
  if (liMatch) {
    const handle = sanitizeHandle(liMatch[1]);
    return handle ? { platform: "l", handle } : null;
  }

  // Bare handle like "@karthik" or "karthik" — assume X.
  const bareHandle = trimmed.match(/^@?([A-Za-z0-9_]+)$/);
  if (bareHandle) {
    const handle = sanitizeHandle(bareHandle[1]);
    return handle ? { platform: "x", handle } : null;
  }

  return null;
}
