const countryCodes = [
  {
    country: "Afghanistan",
    phoneCode: "93",
    symbol: "AF",
    flag: "🇦🇫",
    digits: 9,
  },
  {
    country: "Albania",
    phoneCode: "355",
    symbol: "AL",
    flag: "🇦🇱",
    digits: 9,
  },
  {
    country: "Algeria",
    phoneCode: "213",
    symbol: "DZ",
    flag: "🇩🇿",
    digits: 9,
  },
  {
    country: "American Samoa",
    phoneCode: "1-684",
    symbol: "AS",
    flag: "🇦🇸",
    digits: 10,
  },
  {
    country: "Andorra",
    phoneCode: "376",
    symbol: "AD",
    flag: "🇦🇩",
    digits: 6,
  },
  {
    country: "Angola",
    phoneCode: "244",
    symbol: "AO",
    flag: "🇦🇴",
    digits: 9,
  },
  {
    country: "Anguilla",
    phoneCode: "1-264",
    symbol: "AI",
    flag: "🇦🇮",
    digits: 10,
  },
  {
    country: "Antarctica",
    phoneCode: "672",
    symbol: "AQ",
    flag: "🇦🇶",
    digits: 6,
  },
  {
    country: "Antigua and Barbuda",
    phoneCode: "1-268",
    symbol: "AG",
    flag: "🇦🇬",
    digits: 10,
  },
  {
    country: "Argentina",
    phoneCode: "54",
    symbol: "AR",
    flag: "🇦🇷",
    digits: 10,
  },
  {
    country: "Armenia",
    phoneCode: "374",
    symbol: "AM",
    flag: "🇦🇲",
    digits: 8,
  },
  {
    country: "Aruba",
    phoneCode: "297",
    symbol: "AW",
    flag: "🇦🇼",
    digits: 7,
  },
  {
    country: "Australia",
    phoneCode: "61",
    symbol: "AU",
    flag: "🇦🇺",
    digits: 9,
  },
  {
    country: "Austria",
    phoneCode: "43",
    symbol: "AT",
    flag: "🇦🇹",
    digits: 10,
  },
  {
    country: "Azerbaijan",
    phoneCode: "994",
    symbol: "AZ",
    flag: "🇦🇿",
    digits: 9,
  },
  {
    country: "Bahamas",
    phoneCode: "1-242",
    symbol: "BS",
    flag: "🇧🇸",
    digits: 10,
  },
  {
    country: "Bahrain",
    phoneCode: "973",
    symbol: "BH",
    flag: "🇧🇭",
    digits: 8,
  },
  {
    country: "Bangladesh",
    phoneCode: "880",
    symbol: "BD",
    flag: "🇧🇩",
    digits: 10,
  },
  {
    country: "Barbados",
    phoneCode: "1-246",
    symbol: "BB",
    flag: "🇧🇧",
    digits: 10,
  },
  {
    country: "Belarus",
    phoneCode: "375",
    symbol: "BY",
    flag: "🇧🇾",
    digits: 9,
  },
  {
    country: "Belgium",
    phoneCode: "32",
    symbol: "BE",
    flag: "🇧🇪",
    digits: 9,
  },
  {
    country: "Belize",
    phoneCode: "501",
    symbol: "BZ",
    flag: "🇧🇿",
    digits: 7,
  },
  {
    country: "Benin",
    phoneCode: "229",
    symbol: "BJ",
    flag: "🇧🇯",
    digits: 8,
  },
  {
    country: "Bermuda",
    phoneCode: "1-441",
    symbol: "BM",
    flag: "🇧🇲",
    digits: 10,
  },
  {
    country: "Bhutan",
    phoneCode: "975",
    symbol: "BT",
    flag: "🇧🇹",
    digits: 8,
  },
  {
    country: "Bolivia",
    phoneCode: "591",
    symbol: "BO",
    flag: "🇧🇴",
    digits: 8,
  },
  {
    country: "Bosnia and Herzegovina",
    phoneCode: "387",
    symbol: "BA",
    flag: "🇧🇦",
    digits: 8,
  },
  {
    country: "Botswana",
    phoneCode: "267",
    symbol: "BW",
    flag: "🇧🇼",
    digits: 8,
  },
  {
    country: "Brazil",
    phoneCode: "55",
    symbol: "BR",
    flag: "🇧🇷",
    digits: 11,
  },
  {
    country: "British Indian Ocean Territory",
    phoneCode: "246",
    symbol: "IO",
    flag: "🇮🇴",
    digits: 7,
  },
  {
    country: "British Virgin Islands",
    phoneCode: "1-284",
    symbol: "VG",
    flag: "🇻🇬",
    digits: 10,
  },
  {
    country: "Brunei",
    phoneCode: "673",
    symbol: "BN",
    flag: "🇧🇳",
    digits: 7,
  },
  {
    country: "Bulgaria",
    phoneCode: "359",
    symbol: "BG",
    flag: "🇧🇬",
    digits: 9,
  },
  {
    country: "Burkina Faso",
    phoneCode: "226",
    symbol: "BF",
    flag: "🇧🇫",
    digits: 8,
  },
  {
    country: "Burundi",
    phoneCode: "257",
    symbol: "BI",
    flag: "🇧🇮",
    digits: 8,
  },
  {
    country: "Cambodia",
    phoneCode: "855",
    symbol: "KH",
    flag: "🇰🇭",
    digits: 9,
  },
  {
    country: "Cameroon",
    phoneCode: "237",
    symbol: "CM",
    flag: "🇨🇲",
    digits: 9,
  },
  {
    country: "Canada",
    phoneCode: "1",
    symbol: "CA",
    flag: "🇨🇦",
    digits: 10,
  },
  {
    country: "Cape Verde",
    phoneCode: "238",
    symbol: "CV",
    flag: "🇨🇻",
    digits: 7,
  },
  {
    country: "Cayman Islands",
    phoneCode: "1-345",
    symbol: "KY",
    flag: "🇰🇾",
    digits: 10,
  },
  {
    country: "Central African Republic",
    phoneCode: "236",
    symbol: "CF",
    flag: "🇨🇫",
    digits: 8,
  },
  {
    country: "Chad",
    phoneCode: "235",
    symbol: "TD",
    flag: "🇹🇩",
    digits: 8,
  },
  {
    country: "Chile",
    phoneCode: "56",
    symbol: "CL",
    flag: "🇨🇱",
    digits: 9,
  },
  {
    country: "China",
    phoneCode: "86",
    symbol: "CN",
    flag: "🇨🇳",
    digits: 11,
  },
  {
    country: "Christmas Island",
    phoneCode: "61",
    symbol: "CX",
    flag: "🇨🇽",
    digits: 9,
  },
  {
    country: "Cocos Islands",
    phoneCode: "61",
    symbol: "CC",
    flag: "🇨🇨",
    digits: 9,
  },
  {
    country: "Colombia",
    phoneCode: "57",
    symbol: "CO",
    flag: "🇨🇴",
    digits: 10,
  },
  {
    country: "Comoros",
    phoneCode: "269",
    symbol: "KM",
    flag: "🇰🇲",
    digits: 7,
  },
  {
    country: "Cook Islands",
    phoneCode: "682",
    symbol: "CK",
    flag: "🇨🇰",
    digits: 5,
  },
  {
    country: "Costa Rica",
    phoneCode: "506",
    symbol: "CR",
    flag: "🇨🇷",
    digits: 8,
  },
  {
    country: "Croatia",
    phoneCode: "385",
    symbol: "HR",
    flag: "🇭🇷",
    digits: 9,
  },
  {
    country: "Cuba",
    phoneCode: "53",
    symbol: "CU",
    flag: "🇨🇺",
    digits: 8,
  },
  {
    country: "Curacao",
    phoneCode: "599",
    symbol: "CW",
    flag: "🇨🇼",
    digits: 7,
  },
  {
    country: "Cyprus",
    phoneCode: "357",
    symbol: "CY",
    flag: "🇨🇾",
    digits: 8,
  },
  {
    country: "Czech Republic",
    phoneCode: "420",
    symbol: "CZ",
    flag: "🇨🇿",
    digits: 9,
  },
  {
    country: "Democratic Republic of the Congo",
    phoneCode: "243",
    symbol: "CD",
    flag: "🇨🇩",
    digits: 9,
  },
  {
    country: "Denmark",
    phoneCode: "45",
    symbol: "DK",
    flag: "🇩🇰",
    digits: 8,
  },
  {
    country: "Djibouti",
    phoneCode: "253",
    symbol: "DJ",
    flag: "🇩🇯",
    digits: 8,
  },
  {
    country: "Dominica",
    phoneCode: "1-767",
    symbol: "DM",
    flag: "🇩🇲",
    digits: 10,
  },
  {
    country: "Dominican Republic",
    phoneCode: "1-809",
    symbol: "DO",
    flag: "🇩🇴",
    digits: 10,
  },
  {
    country: "East Timor",
    phoneCode: "670",
    symbol: "TL",
    flag: "🇹🇱",
    digits: 8,
  },
  {
    country: "Ecuador",
    phoneCode: "593",
    symbol: "EC",
    flag: "🇪🇨",
    digits: 9,
  },
  {
    country: "Egypt",
    phoneCode: "20",
    symbol: "EG",
    flag: "🇪🇬",
    digits: 10,
  },
  {
    country: "El Salvador",
    phoneCode: "503",
    symbol: "SV",
    flag: "🇸🇻",
    digits: 8,
  },
  {
    country: "Equatorial Guinea",
    phoneCode: "240",
    symbol: "GQ",
    flag: "🇬🇶",
    digits: 9,
  },
  {
    country: "Eritrea",
    phoneCode: "291",
    symbol: "ER",
    flag: "🇪🇷",
    digits: 7,
  },
  {
    country: "Estonia",
    phoneCode: "372",
    symbol: "EE",
    flag: "🇪🇪",
    digits: 8,
  },
  {
    country: "Ethiopia",
    phoneCode: "251",
    symbol: "ET",
    flag: "🇪🇹",
    digits: 9,
  },
  {
    country: "Falkland Islands",
    phoneCode: "500",
    symbol: "FK",
    flag: "🇫🇰",
    digits: 5,
  },
  {
    country: "Faroe Islands",
    phoneCode: "298",
    symbol: "FO",
    flag: "🇫🇴",
    digits: 6,
  },
  {
    country: "Fiji",
    phoneCode: "679",
    symbol: "FJ",
    flag: "🇫🇯",
    digits: 7,
  },
  {
    country: "Finland",
    phoneCode: "358",
    symbol: "FI",
    flag: "🇫🇮",
    digits: 10,
  },
  {
    country: "France",
    phoneCode: "33",
    symbol: "FR",
    flag: "🇫🇷",
    digits: 9,
  },
  {
    country: "French Polynesia",
    phoneCode: "689",
    symbol: "PF",
    flag: "🇵🇫",
    digits: 6,
  },
  {
    country: "Gabon",
    phoneCode: "241",
    symbol: "GA",
    flag: "🇬🇦",
    digits: 8,
  },
  {
    country: "Gambia",
    phoneCode: "220",
    symbol: "GM",
    flag: "🇬🇲",
    digits: 7,
  },
  {
    country: "Georgia",
    phoneCode: "995",
    symbol: "GE",
    flag: "🇬🇪",
    digits: 9,
  },
  {
    country: "Germany",
    phoneCode: "49",
    symbol: "DE",
    flag: "🇩🇪",
    digits: 11,
  },
  {
    country: "Ghana",
    phoneCode: "233",
    symbol: "GH",
    flag: "🇬🇭",
    digits: 9,
  },
  {
    country: "Gibraltar",
    phoneCode: "350",
    symbol: "GI",
    flag: "🇬🇮",
    digits: 8,
  },
  {
    country: "Greece",
    phoneCode: "30",
    symbol: "GR",
    flag: "🇬🇷",
    digits: 10,
  },
  {
    country: "Greenland",
    phoneCode: "299",
    symbol: "GL",
    flag: "🇬🇱",
    digits: 6,
  },
  {
    country: "Grenada",
    phoneCode: "1-473",
    symbol: "GD",
    flag: "🇬🇩",
    digits: 10,
  },
  {
    country: "Guam",
    phoneCode: "1-671",
    symbol: "GU",
    flag: "🇬🇺",
    digits: 10,
  },
  {
    country: "Guatemala",
    phoneCode: "502",
    symbol: "GT",
    flag: "🇬🇹",
    digits: 8,
  },
  {
    country: "Guernsey",
    phoneCode: "44-1481",
    symbol: "GG",
    flag: "🇬🇬",
    digits: 10,
  },
  {
    country: "Guinea",
    phoneCode: "224",
    symbol: "GN",
    flag: "🇬🇳",
    digits: 9,
  },
  {
    country: "Guinea-Bissau",
    phoneCode: "245",
    symbol: "GW",
    flag: "🇬🇼",
    digits: 7,
  },
  {
    country: "Guyana",
    phoneCode: "592",
    symbol: "GY",
    flag: "🇬🇾",
    digits: 7,
  },
  {
    country: "Haiti",
    phoneCode: "509",
    symbol: "HT",
    flag: "🇭🇹",
    digits: 8,
  },
  {
    country: "Honduras",
    phoneCode: "504",
    symbol: "HN",
    flag: "🇭🇳",
    digits: 8,
  },
  {
    country: "Hong Kong",
    phoneCode: "852",
    symbol: "HK",
    flag: "🇭🇰",
    digits: 8,
  },
  {
    country: "Hungary",
    phoneCode: "36",
    symbol: "HU",
    flag: "🇭🇺",
    digits: 9,
  },
  {
    country: "Iceland",
    phoneCode: "354",
    symbol: "IS",
    flag: "🇮🇸",
    digits: 7,
  },
  {
    country: "India",
    phoneCode: "91",
    symbol: "IN",
    flag: "🇮🇳",
    digits: 10,
  },
  {
    country: "Indonesia",
    phoneCode: "62",
    symbol: "ID",
    flag: "🇮🇩",
    digits: 10,
  },
  {
    country: "Iran",
    phoneCode: "98",
    symbol: "IR",
    flag: "🇮🇷",
    digits: 10,
  },
  {
    country: "Iraq",
    phoneCode: "964",
    symbol: "IQ",
    flag: "🇮🇶",
    digits: 10,
  },
  {
    country: "Ireland",
    phoneCode: "353",
    symbol: "IE",
    flag: "🇮🇪",
    digits: 9,
  },
  {
    country: "Isle of Man",
    phoneCode: "44-1624",
    symbol: "IM",
    flag: "🇮🇲",
    digits: 10,
  },
  {
    country: "Israel",
    phoneCode: "972",
    symbol: "IL",
    flag: "🇮🇱",
    digits: 9,
  },
  {
    country: "Italy",
    phoneCode: "39",
    symbol: "IT",
    flag: "🇮🇹",
    digits: 10,
  },
  {
    country: "Ivory Coast",
    phoneCode: "225",
    symbol: "CI",
    flag: "🇨🇮",
    digits: 8,
  },
  {
    country: "Jamaica",
    phoneCode: "1-876",
    symbol: "JM",
    flag: "🇯🇲",
    digits: 10,
  },
  {
    country: "Japan",
    phoneCode: "81",
    symbol: "JP",
    flag: "🇯🇵",
    digits: 10,
  },
  {
    country: "Jersey",
    phoneCode: "44-1534",
    symbol: "JE",
    flag: "🇯🇪",
    digits: 10,
  },
  {
    country: "Jordan",
    phoneCode: "962",
    symbol: "JO",
    flag: "🇯🇴",
    digits: 9,
  },
  {
    country: "Kazakhstan",
    phoneCode: "7",
    symbol: "KZ",
    flag: "🇰🇿",
    digits: 10,
  },
  {
    country: "Kenya",
    phoneCode: "254",
    symbol: "KE",
    flag: "🇰🇪",
    digits: 9,
  },
  {
    country: "Kiribati",
    phoneCode: "686",
    symbol: "KI",
    flag: "🇰🇮",
    digits: 5,
  },
  {
    country: "Kosovo",
    phoneCode: "383",
    symbol: "XK",
    flag: "🇽🇰",
    digits: 8,
  },
  {
    country: "Kuwait",
    phoneCode: "965",
    symbol: "KW",
    flag: "🇰🇼",
    digits: 8,
  },
  {
    country: "Kyrgyzstan",
    phoneCode: "996",
    symbol: "KG",
    flag: "🇰🇬",
    digits: 9,
  },
  {
    country: "Laos",
    phoneCode: "856",
    symbol: "LA",
    flag: "🇱🇦",
    digits: 10,
  },
  {
    country: "Latvia",
    phoneCode: "371",
    symbol: "LV",
    flag: "🇱🇻",
    digits: 8,
  },
  {
    country: "Lebanon",
    phoneCode: "961",
    symbol: "LB",
    flag: "🇱🇧",
    digits: 8,
  },
  {
    country: "Lesotho",
    phoneCode: "266",
    symbol: "LS",
    flag: "🇱🇸",
    digits: 8,
  },
  {
    country: "Liberia",
    phoneCode: "231",
    symbol: "LR",
    flag: "🇱🇷",
    digits: 8,
  },
  {
    country: "Libya",
    phoneCode: "218",
    symbol: "LY",
    flag: "🇱🇾",
    digits: 9,
  },
  {
    country: "Liechtenstein",
    phoneCode: "423",
    symbol: "LI",
    flag: "🇱🇮",
    digits: 7,
  },
  {
    country: "Lithuania",
    phoneCode: "370",
    symbol: "LT",
    flag: "🇱🇹",
    digits: 8,
  },
  {
    country: "Luxembourg",
    phoneCode: "352",
    symbol: "LU",
    flag: "🇱🇺",
    digits: 9,
  },
  {
    country: "Macau",
    phoneCode: "853",
    symbol: "MO",
    flag: "🇲🇴",
    digits: 8,
  },
  {
    country: "Macedonia",
    phoneCode: "389",
    symbol: "MK",
    flag: "🇲🇰",
    digits: 8,
  },
  {
    country: "Madagascar",
    phoneCode: "261",
    symbol: "MG",
    flag: "🇲🇬",
    digits: 9,
  },
  {
    country: "Malawi",
    phoneCode: "265",
    symbol: "MW",
    flag: "🇲🇼",
    digits: 9,
  },
  {
    country: "Malaysia",
    phoneCode: "60",
    symbol: "MY",
    flag: "🇲🇾",
    digits: 9,
  },
  {
    country: "Maldives",
    phoneCode: "960",
    symbol: "MV",
    flag: "🇲🇻",
    digits: 7,
  },
  {
    country: "Mali",
    phoneCode: "223",
    symbol: "ML",
    flag: "🇲🇱",
    digits: 8,
  },
  {
    country: "Malta",
    phoneCode: "356",
    symbol: "MT",
    flag: "🇲🇹",
    digits: 8,
  },
  {
    country: "Marshall Islands",
    phoneCode: "692",
    symbol: "MH",
    flag: "🇲🇭",
    digits: 7,
  },
  {
    country: "Mauritania",
    phoneCode: "222",
    symbol: "MR",
    flag: "🇲🇷",
    digits: 8,
  },
  {
    country: "Mauritius",
    phoneCode: "230",
    symbol: "MU",
    flag: "🇲🇺",
    digits: 8,
  },
  {
    country: "Mexico",
    phoneCode: "52",
    symbol: "MX",
    flag: "🇲🇽",
    digits: 10,
  },
  {
    country: "Micronesia",
    phoneCode: "691",
    symbol: "FM",
    flag: "🇫🇲",
    digits: 7,
  },
  {
    country: "Moldova",
    phoneCode: "373",
    symbol: "MD",
    flag: "🇲🇩",
    digits: 8,
  },
  {
    country: "Monaco",
    phoneCode: "377",
    symbol: "MC",
    flag: "🇲🇨",
    digits: 8,
  },
  {
    country: "Mongolia",
    phoneCode: "976",
    symbol: "MN",
    flag: "🇲🇳",
    digits: 8,
  },
  {
    country: "Montenegro",
    phoneCode: "382",
    symbol: "ME",
    flag: "🇲🇪",
    digits: 8,
  },
  {
    country: "Morocco",
    phoneCode: "212",
    symbol: "MA",
    flag: "🇲🇦",
    digits: 9,
  },
  {
    country: "Mozambique",
    phoneCode: "258",
    symbol: "MZ",
    flag: "🇲🇿",
    digits: 9,
  },
  {
    country: "Myanmar",
    phoneCode: "95",
    symbol: "MM",
    flag: "🇲🇲",
    digits: 9,
  },
  {
    country: "Namibia",
    phoneCode: "264",
    symbol: "NA",
    flag: "🇳🇦",
    digits: 9,
  },
  {
    country: "Nepal",
    phoneCode: "977",
    symbol: "NP",
    flag: "🇳🇵",
    digits: 10,
  },
  {
    country: "Netherlands",
    phoneCode: "31",
    symbol: "NL",
    flag: "🇳🇱",
    digits: 9,
  },
  {
    country: "New Caledonia",
    phoneCode: "687",
    symbol: "NC",
    flag: "🇳🇨",
    digits: 6,
  },
  {
    country: "New Zealand",
    phoneCode: "64",
    symbol: "NZ",
    flag: "🇳🇿",
    digits: 9,
  },
  {
    country: "Nicaragua",
    phoneCode: "505",
    symbol: "NI",
    flag: "🇳🇮",
    digits: 8,
  },
  {
    country: "Niger",
    phoneCode: "227",
    symbol: "NE",
    flag: "🇳🇪",
    digits: 8,
  },
  {
    country: "Nigeria",
    phoneCode: "234",
    symbol: "NG",
    flag: "🇳🇬",
    digits: 10,
  },
  {
    country: "North Korea",
    phoneCode: "850",
    symbol: "KP",
    flag: "🇰🇵",
    digits: 10,
  },
  {
    country: "Norway",
    phoneCode: "47",
    symbol: "NO",
    flag: "🇳🇴",
    digits: 8,
  },
  {
    country: "Oman",
    phoneCode: "968",
    symbol: "OM",
    flag: "🇴🇲",
    digits: 8,
  },
  {
    country: "Pakistan",
    phoneCode: "92",
    symbol: "PK",
    flag: "🇵🇰",
    digits: 10,
  },
  {
    country: "Palau",
    phoneCode: "680",
    symbol: "PW",
    flag: "🇵🇼",
    digits: 7,
  },
  {
    country: "Palestine",
    phoneCode: "970",
    symbol: "PS",
    flag: "🇵🇸",
    digits: 9,
  },
  {
    country: "Panama",
    phoneCode: "507",
    symbol: "PA",
    flag: "🇵🇦",
    digits: 8,
  },
  {
    country: "Papua New Guinea",
    phoneCode: "675",
    symbol: "PG",
    flag: "🇵🇬",
    digits: 8,
  },
  {
    country: "Paraguay",
    phoneCode: "595",
    symbol: "PY",
    flag: "🇵🇾",
    digits: 9,
  },
  {
    country: "Peru",
    phoneCode: "51",
    symbol: "PE",
    flag: "🇵🇪",
    digits: 9,
  },
  {
    country: "Philippines",
    phoneCode: "63",
    symbol: "PH",
    flag: "🇵🇭",
    digits: 10,
  },
  {
    country: "Poland",
    phoneCode: "48",
    symbol: "PL",
    flag: "🇵🇱",
    digits: 9,
  },
  {
    country: "Portugal",
    phoneCode: "351",
    symbol: "PT",
    flag: "🇵🇹",
    digits: 9,
  },
  {
    country: "Puerto Rico",
    phoneCode: "1-787",
    symbol: "PR",
    flag: "🇵🇷",
    digits: 10,
  },
  {
    country: "Qatar",
    phoneCode: "974",
    symbol: "QA",
    flag: "🇶🇦",
    digits: 8,
  },
  {
    country: "Republic of the Congo",
    phoneCode: "242",
    symbol: "CG",
    flag: "🇨🇬",
    digits: 9,
  },
  {
    country: "Romania",
    phoneCode: "40",
    symbol: "RO",
    flag: "🇷🇴",
    digits: 10,
  },
  {
    country: "Russia",
    phoneCode: "7",
    symbol: "RU",
    flag: "🇷🇺",
    digits: 10,
  },
  {
    country: "Rwanda",
    phoneCode: "250",
    symbol: "RW",
    flag: "🇷🇼",
    digits: 9,
  },
  {
    country: "Saint Kitts and Nevis",
    phoneCode: "1-869",
    symbol: "KN",
    flag: "🇰🇳",
    digits: 10,
  },
  {
    country: "Saint Lucia",
    phoneCode: "1-758",
    symbol: "LC",
    flag: "🇱🇨",
    digits: 10,
  },
  {
    country: "Saint Vincent and the Grenadines",
    phoneCode: "1-784",
    symbol: "VC",
    flag: "🇻🇨",
    digits: 10,
  },
  {
    country: "Samoa",
    phoneCode: "685",
    symbol: "WS",
    flag: "🇼🇸",
    digits: 7,
  },
  {
    country: "San Marino",
    phoneCode: "378",
    symbol: "SM",
    flag: "🇸🇲",
    digits: 8,
  },
  {
    country: "Sao Tome and Principe",
    phoneCode: "239",
    symbol: "ST",
    flag: "🇸🇹",
    digits: 7,
  },
  {
    country: "Saudi Arabia",
    phoneCode: "966",
    symbol: "SA",
    flag: "🇸🇦",
    digits: 9,
  },
  {
    country: "Senegal",
    phoneCode: "221",
    symbol: "SN",
    flag: "🇸🇳",
    digits: 9,
  },
  {
    country: "Serbia",
    phoneCode: "381",
    symbol: "RS",
    flag: "🇷🇸",
    digits: 9,
  },
  {
    country: "Seychelles",
    phoneCode: "248",
    symbol: "SC",
    flag: "🇸🇨",
    digits: 7,
  },
  {
    country: "Sierra Leone",
    phoneCode: "232",
    symbol: "SL",
    flag: "🇸🇱",
    digits: 8,
  },
  {
    country: "Singapore",
    phoneCode: "65",
    symbol: "SG",
    flag: "🇸🇬",
    digits: 8,
  },
  {
    country: "Slovakia",
    phoneCode: "421",
    symbol: "SK",
    flag: "🇸🇰",
    digits: 9,
  },
  {
    country: "Slovenia",
    phoneCode: "386",
    symbol: "SI",
    flag: "🇸🇮",
    digits: 8,
  },
  {
    country: "Solomon Islands",
    phoneCode: "677",
    symbol: "SB",
    flag: "🇸🇧",
    digits: 7,
  },
  {
    country: "Somalia",
    phoneCode: "252",
    symbol: "SO",
    flag: "🇸🇴",
    digits: 8,
  },
  {
    country: "South Africa",
    phoneCode: "27",
    symbol: "ZA",
    flag: "🇿🇦",
    digits: 9,
  },
  {
    country: "South Korea",
    phoneCode: "82",
    symbol: "KR",
    flag: "🇰🇷",
    digits: 10,
  },
  {
    country: "South Sudan",
    phoneCode: "211",
    symbol: "SS",
    flag: "🇸🇸",
    digits: 9,
  },
  {
    country: "Spain",
    phoneCode: "34",
    symbol: "ES",
    flag: "🇪🇸",
    digits: 9,
  },
  {
    country: "Sri Lanka",
    phoneCode: "94",
    symbol: "LK",
    flag: "🇱🇰",
    digits: 9,
  },
  {
    country: "Sudan",
    phoneCode: "249",
    symbol: "SD",
    flag: "🇸🇩",
    digits: 9,
  },
  {
    country: "Suriname",
    phoneCode: "597",
    symbol: "SR",
    flag: "🇸🇷",
    digits: 7,
  },
  {
    country: "Swaziland",
    phoneCode: "268",
    symbol: "SZ",
    flag: "🇸🇿",
    digits: 8,
  },
  {
    country: "Sweden",
    phoneCode: "46",
    symbol: "SE",
    flag: "🇸🇪",
    digits: 9,
  },
  {
    country: "Switzerland",
    phoneCode: "41",
    symbol: "CH",
    flag: "🇨🇭",
    digits: 9,
  },
  {
    country: "Syria",
    phoneCode: "963",
    symbol: "SY",
    flag: "🇸🇾",
    digits: 9,
  },
  {
    country: "Taiwan",
    phoneCode: "886",
    symbol: "TW",
    flag: "🇹🇼",
    digits: 9,
  },
  {
    country: "Tajikistan",
    phoneCode: "992",
    symbol: "TJ",
    flag: "🇹🇯",
    digits: 9,
  },
  {
    country: "Tanzania",
    phoneCode: "255",
    symbol: "TZ",
    flag: "🇹🇿",
    digits: 9,
  },
  {
    country: "Thailand",
    phoneCode: "66",
    symbol: "TH",
    flag: "🇹🇭",
    digits: 9,
  },
  {
    country: "Togo",
    phoneCode: "228",
    symbol: "TG",
    flag: "🇹🇬",
    digits: 8,
  },
  {
    country: "Tonga",
    phoneCode: "676",
    symbol: "TO",
    flag: "🇹🇴",
    digits: 7,
  },
  {
    country: "Trinidad and Tobago",
    phoneCode: "1-868",
    symbol: "TT",
    flag: "🇹🇹",
    digits: 10,
  },
  {
    country: "Tunisia",
    phoneCode: "216",
    symbol: "TN",
    flag: "🇹🇳",
    digits: 8,
  },
  {
    country: "Turkey",
    phoneCode: "90",
    symbol: "TR",
    flag: "🇹🇷",
    digits: 10,
  },
  {
    country: "Turkmenistan",
    phoneCode: "993",
    symbol: "TM",
    flag: "🇹🇲",
    digits: 8,
  },
  {
    country: "Uganda",
    phoneCode: "256",
    symbol: "UG",
    flag: "🇺🇬",
    digits: 9,
  },
  {
    country: "Ukraine",
    phoneCode: "380",
    symbol: "UA",
    flag: "🇺🇦",
    digits: 9,
  },
  {
    country: "United Arab Emirates",
    phoneCode: "971",
    symbol: "AE",
    flag: "🇦🇪",
    digits: 9,
  },
  {
    country: "United Kingdom",
    phoneCode: "44",
    symbol: "GB",
    flag: "🇬🇧",
    digits: 10,
  },
  {
    country: "United States",
    phoneCode: "1",
    symbol: "US",
    flag: "🇺🇸",
    digits: 10,
  },
  {
    country: "Uruguay",
    phoneCode: "598",
    symbol: "UY",
    flag: "🇺🇾",
    digits: 8,
  },
  {
    country: "Uzbekistan",
    phoneCode: "998",
    symbol: "UZ",
    flag: "🇺🇿",
    digits: 9,
  },
  {
    country: "Vanuatu",
    phoneCode: "678",
    symbol: "VU",
    flag: "🇻🇺",
    digits: 7,
  },
  {
    country: "Vatican",
    phoneCode: "379",
    symbol: "VA",
    flag: "🇻🇦",
    digits: 10,
  },
  {
    country: "Venezuela",
    phoneCode: "58",
    symbol: "VE",
    flag: "🇻🇪",
    digits: 10,
  },
  {
    country: "Vietnam",
    phoneCode: "84",
    symbol: "VN",
    flag: "🇻🇳",
    digits: 9,
  },
  {
    country: "Yemen",
    phoneCode: "967",
    symbol: "YE",
    flag: "🇾🇪",
    digits: 9,
  },
  {
    country: "Zambia",
    phoneCode: "260",
    symbol: "ZM",
    flag: "🇿🇲",
    digits: 9,
  },
  {
    country: "Zimbabwe",
    phoneCode: "263",
    symbol: "ZW",
    flag: "🇿🇼",
    digits: 9,
  },
];

export default countryCodes;
