import { Trait } from '../types';

export const baesTraits: Record<string, Trait[]> = {
  skin: [{ id: 0, name: 'Zo', weight: 0 }],
  background: [
    { id: -1, name: null, weight: 20 },
    { id: 0, name: 'Day', weight: 5 },
    { id: 1, name: 'Wonka', weight: 5 },
    { id: 2, name: 'Dew', weight: 5 },
    { id: 3, name: 'Cyan', weight: 5 },
    { id: 4, name: 'Superman', weight: 4 },
    { id: 6, name: 'Lego', weight: 4 },
    { id: 7, name: 'Lyft', weight: 4 },
    { id: 8, name: 'Twitch', weight: 4 },
    { id: 9, name: 'Sprite', weight: 4 },
    { id: 10, name: 'Sky', weight: 4 },
    { id: 11, name: 'Cherry', weight: 4 },
    { id: 12, name: 'Marine', weight: 4 },
    { id: 13, name: 'Thar', weight: 4 },
    { id: 14, name: 'Peach', weight: 4 },
    { id: 16, name: 'Ceramic', weight: 4 },
    { id: 17, name: 'Stick', weight: 4 },
    { id: 18, name: 'Swamp', weight: 4 },
    { id: 19, name: 'Woods', weight: 4 },
  ],
  eyewear: [
    { id: -1, name: null, weight: 20 },
    { id: 0, name: 'Miami', weight: 4 },
    { id: 1, name: 'Office', weight: 4 },
    { id: 2, name: 'Matrix', weight: 4 },
    { id: 3, name: '3D', weight: 4 },
    { id: 4, name: 'Pirate', weight: 4 },
    { id: 5, name: 'Potter', weight: 4 },
    { id: 6, name: 'Vegas', weight: 4 },
    { id: 7, name: 'Gandhi', weight: 4 },
    { id: 8, name: 'Vision', weight: 4 },
    { id: 9, name: 'X-Men', weight: 4 },
    { id: 10, name: 'Pimp', weight: 4 },
    { id: 12, name: 'Love', weight: 4 },
    { id: 13, name: 'DJ', weight: 4 },
    { id: 14, name: 'Tech', weight: 4 },
    { id: 15, name: 'Thug', weight: 4 },
    { id: 16, name: 'Zorro', weight: 4 },
    { id: 17, name: 'Android', weight: 4 },
    { id: 18, name: 'Noun', weight: 4 },
    { id: 19, name: 'Woke', weight: 4 },
    { id: 20, name: 'Cat Eye', weight: 4 },
  ],
  dress: [
    { id: -1, name: null, weight: 20 },
    { id: 0, name: 'Zo', weight: 2 },
    { id: 1, name: 'Matrix', weight: 2 },
    { id: 2, name: 'Sequin', weight: 2 },
    { id: 3, name: 'Pink', weight: 2 },
    { id: 4, name: 'Avril', weight: 2 },
    { id: 5, name: 'Olive', weight: 2 },
    { id: 6, name: 'Sweetheart', weight: 2 },
    { id: 7, name: 'Violet', weight: 2 },
    { id: 8, name: 'Peach', weight: 2 },
    { id: 9, name: 'Diana', weight: 2 },
    { id: 10, name: 'Trinity', weight: 2 },
    { id: 11, name: 'Kate', weight: 2 },
    { id: 12, name: 'Revenge', weight: 2 },
    { id: 13, name: 'Little Red Riding Hood', weight: 2 },
    { id: 14, name: 'Puffer', weight: 2 },
    { id: 15, name: 'Track', weight: 2 },
    { id: 16, name: 'Olive Oyl', weight: 2 },
    { id: 17, name: 'Army', weight: 2 },
    { id: 18, name: 'Navy', weight: 2 },
    { id: 19, name: 'Air Force', weight: 2 },
    { id: 20, name: 'Space', weight: 2 },
    { id: 21, name: 'Chan', weight: 2 },
    { id: 22, name: 'Guantanamo', weight: 2 },
    { id: 23, name: 'Ride', weight: 2 },
    { id: 24, name: 'Farming', weight: 2 },
    { id: 25, name: 'Astronaut', weight: 2 },
    { id: 26, name: 'Kimono', weight: 2 },
    { id: 27, name: 'Kill', weight: 2 },
    { id: 28, name: 'Law', weight: 2 },
    { id: 29, name: 'Nine-Nine', weight: 2 },
    { id: 30, name: 'Mithali', weight: 2 },
    { id: 31, name: 'Cold', weight: 2 },
    { id: 32, name: 'Eskimo', weight: 2 },
    { id: 33, name: 'Margaret', weight: 2 },
    { id: 34, name: 'Saree', weight: 2 },
    { id: 35, name: 'Summer', weight: 2 },
    { id: 36, name: 'Lime', weight: 2 },
    { id: 37, name: 'Velma', weight: 2 },
    { id: 38, name: 'Lara Croft', weight: 2 },
    { id: 39, name: 'Malaga', weight: 2 },
    { id: 40, name: 'Wonder Woman', weight: 2 },
    { id: 41, name: 'Ana', weight: 2 },
    { id: 42, name: 'Alicia', weight: 2 },
  ],
  mouth: [
    { id: 0, name: 'Smile', weight: 0 },
    { id: 1, name: 'Smile', weight: 0 },
    { id: 2, name: 'Ivy', weight: 0 },
    { id: 3, name: '420', weight: 0 },
    { id: 4, name: 'Bleb', weight: 0 },
    { id: 5, name: 'vape', weight: 0 },
    { id: 6, name: 'Havana', weight: 0 },
    { id: 7, name: 'Tobacco', weight: 0 },
    { id: 8, name: 'NYC', weight: 0 },
    { id: 9, name: 'Party', weight: 0 },
    { id: 10, name: 'Mexico', weight: 0 },
    { id: 11, name: 'Seville', weight: 0 },
    { id: 12, name: 'Pizza', weight: 0 },
    { id: 13, name: 'Lollypop', weight: 0 },
    { id: 14, name: 'Rich', weight: 0 },
    { id: 15, name: 'Sic', weight: 0 },
    { id: 16, name: 'Wow', weight: 0 },
    { id: 17, name: 'Love', weight: 0 },
    { id: 18, name: 'Blah', weight: 0 },
    { id: 19, name: 'Chandigarh', weight: 0 },
  ],
  earrings: [
    { id: -1, name: null, weight: 20 },
    { id: 0, name: 'Leaf', weight: 7 },
    { id: 1, name: 'Tops', weight: 7 },
    { id: 2, name: 'Pearl', weight: 7 },
    { id: 3, name: 'Cuffs', weight: 7 },
    { id: 4, name: 'Ruby', weight: 7 },
    { id: 5, name: 'Violet', weight: 7 },
    { id: 6, name: 'Floral', weight: 7 },
    { id: 7, name: 'Hearts', weight: 7 },
    { id: 8, name: 'Emarald', weight: 7 },
    { id: 9, name: 'Sapphire', weight: 7 },
    { id: 10, name: 'Hoops', weight: 7 },
    { id: 11, name: 'Gold', weight: 7 },
  ],
  head: [
    { id: -1, name: null, weight: 20 },
    { id: 0, name: 'AirPods', weight: 13 },
    { id: 1, name: 'Angel', weight: 13 },
    { id: 2, name: 'Hell', weight: 13 },
    { id: 3, name: 'Music', weight: 13 },
    { id: 4, name: 'Blossom', weight: 13 },
    { id: 5, name: 'Frida Kahlo', weight: 13 },
  ],
  neck: [
    { id: -1, name: null, weight: 20 },
    { id: 0, name: 'Scarf', weight: 6 },
    { id: 1, name: 'Pearls', weight: 6 },
    { id: 2, name: 'Ruby', weight: 6 },
    { id: 3, name: 'Gold', weight: 6 },
    { id: 4, name: 'Bow', weight: 6 },
    { id: 5, name: 'Floral', weight: 6 },
    { id: 6, name: 'Everland', weight: 6 },
    { id: 7, name: 'Hearts', weight: 6 },
    { id: 8, name: 'Olive', weight: 6 },
    { id: 9, name: 'Shay', weight: 6 },
    { id: 10, name: 'Candy', weight: 6 },
    { id: 11, name: 'Diamonds', weight: 6 },
    { id: 12, name: 'Choker', weight: 6 },
  ],
  eyes: [
    { id: 0, name: 'Angry', weight: 0 },
    { id: 1, name: 'Happy', weight: 0 },
    { id: 2, name: 'Sic', weight: 0 },
    { id: 3, name: 'Dead', weight: 0 },
    { id: 4, name: 'Hypnotised', weight: 0 },
    { id: 7, name: 'Love', weight: 0 },
    { id: 8, name: 'Sus', weight: 0 },
    { id: 9, name: 'Wow', weight: 0 },
    { id: 10, name: 'Wut', weight: 0 },
    { id: 11, name: 'Gotcha', weight: 0 },
  ],
  hair: [
    { id: -1, name: null, weight: 20 },
    { id: 0, name: 'Harley Quinn', weight: 6 },
    { id: 1, name: 'Velma', weight: 6 },
    { id: 2, name: 'Pigtails', weight: 6 },
    { id: 3, name: 'Farrah', weight: 6 },
    { id: 4, name: 'Ariel', weight: 6 },
    { id: 5, name: 'Leia', weight: 6 },
    { id: 6, name: 'Cher', weight: 6 },
    { id: 7, name: 'Ellen', weight: 6 },
    { id: 8, name: 'Half Shaven', weight: 6 },
    { id: 9, name: 'Ariana', weight: 6 },
    { id: 10, name: 'Shaved', weight: 6 },
    { id: 11, name: 'Mohawk', weight: 6 },
    { id: 12, name: 'Braids', weight: 6 },
    { id: 13, name: 'Platinum Waves', weight: 6 },
  ],
};
