import { Trait } from '../types';

export const brosTraits: Record<string, Trait[]> = {
  skin: [{ id: 0, name: 'Zo', weight: 0 }],
  background: [
    { id: -1, name: null, weight: 20 },
    { id: 0, name: 'Day', weight: 4 },
    { id: 1, name: 'Wonka', weight: 4 },
    { id: 2, name: 'Dew', weight: 4 },
    { id: 3, name: 'Cyan', weight: 4 },
    { id: 4, name: 'Superman', weight: 4 },
    { id: 6, name: 'Lego', weight: 4 },
    { id: 7, name: 'Lyft', weight: 4 },
    { id: 8, name: 'Twitch', weight: 4 },
    { id: 9, name: 'Sprite', weight: 4 },
    { id: 10, name: 'Sky', weight: 4 },
    { id: 11, name: 'Cherry', weight: 4 },
    { id: 12, name: 'Marine', weight: 4 },
    { id: 13, name: 'Thar', weight: 4 },
    { id: 14, name: 'Peach', weight: 4 },
    { id: 16, name: 'Ceramic', weight: 4 },
    { id: 17, name: 'Stick', weight: 4 },
    { id: 18, name: 'Swamp', weight: 4 },
    { id: 19, name: 'Woods', weight: 4 },
  ],
  eyewear: [
    { id: -1, name: null, weight: 20 },
    { id: 0, name: 'Miami', weight: 4 },
    { id: 1, name: 'Office', weight: 4 },
    { id: 2, name: 'Matrix', weight: 4 },
    { id: 3, name: '3D', weight: 4 },
    { id: 4, name: 'Pirate', weight: 4 },
    { id: 5, name: 'Potter', weight: 4 },
    { id: 6, name: 'Vegas', weight: 4 },
    { id: 7, name: 'Gandhi', weight: 4 },
    { id: 8, name: 'Vision', weight: 4 },
    { id: 9, name: 'X-Men', weight: 4 },
    { id: 10, name: 'Pimp', weight: 4 },
    { id: 12, name: 'Love', weight: 4 },
    { id: 13, name: 'DJ', weight: 4 },
    { id: 14, name: 'Tech', weight: 4 },
    { id: 15, name: 'Thug', weight: 4 },
    { id: 16, name: 'Zorro', weight: 4 },
    { id: 17, name: 'Android', weight: 4 },
    { id: 18, name: 'Noun', weight: 4 },
    { id: 19, name: 'Woke', weight: 4 },
    { id: 20, name: 'Starboy', weight: 4 },
  ],
  dress: [
    { id: -1, name: null, weight: 20 },
    { id: 0, name: 'Amsterdam', weight: 2 },
    { id: 1, name: 'Jobs', weight: 2 },
    { id: 2, name: 'Kobe', weight: 2 },
    { id: 3, name: 'Jordan', weight: 2 },
    { id: 4, name: 'Lacoste', weight: 2 },
    { id: 5, name: 'Lahore', weight: 2 },
    { id: 6, name: 'Uber', weight: 2 },
    { id: 7, name: 'Party', weight: 2 },
    { id: 8, name: 'Sailor', weight: 2 },
    { id: 9, name: 'MIB', weight: 2 },
    { id: 10, name: 'Gala', weight: 2 },
    { id: 11, name: 'Saul', weight: 2 },
    { id: 12, name: 'Hack', weight: 2 },
    { id: 13, name: 'Eminem', weight: 2 },
    { id: 14, name: 'Puffer', weight: 2 },
    { id: 15, name: 'Fairbanks', weight: 2 },
    { id: 16, name: 'Poker', weight: 2 },
    { id: 17, name: 'LA', weight: 2 },
    { id: 18, name: 'Track', weight: 2 },
    { id: 19, name: 'Malibu', weight: 2 },
    { id: 20, name: 'Night', weight: 2 },
    { id: 21, name: 'Virginia', weight: 2 },
    { id: 22, name: 'Rio', weight: 2 },
    { id: 23, name: 'Malaga', weight: 2 },
    { id: 24, name: 'Bavaria', weight: 2 },
    { id: 25, name: 'Night', weight: 2 },
    { id: 26, name: 'Sky', weight: 2 },
    { id: 27, name: 'Amazon', weight: 2 },
    { id: 28, name: 'Army', weight: 2 },
    { id: 29, name: 'Navy', weight: 2 },
    { id: 30, name: 'Air Force', weight: 2 },
    { id: 31, name: 'Popeye', weight: 2 },
    { id: 32, name: 'Space', weight: 2 },
    { id: 33, name: 'Rich', weight: 2 },
    { id: 34, name: 'Guantanamo', weight: 2 },
    { id: 35, name: 'Ride', weight: 2 },
    { id: 36, name: 'Farming', weight: 2 },
    { id: 37, name: 'Space', weight: 2 },
    { id: 38, name: 'Knight', weight: 2 },
    { id: 39, name: 'Bull', weight: 2 },
    { id: 40, name: 'Wall Street', weight: 2 },
    { id: 41, name: 'King', weight: 2 },
    { id: 42, name: 'Jodhpur', weight: 2 },
    { id: 43, name: 'Agra', weight: 2 },
    { id: 44, name: 'Smart', weight: 2 },
    { id: 45, name: 'Boston', weight: 2 },
    { id: 46, name: 'Cold', weight: 2 },
    { id: 47, name: 'NYC', weight: 2 },
    { id: 49, name: 'Tendulkar', weight: 2 },
    { id: 50, name: 'Fufa', weight: 2 },
    { id: 51, name: 'Cupid', weight: 2 },
    { id: 52, name: 'Gold', weight: 2 },
    { id: 53, name: 'Samurai', weight: 2 },
    { id: 54, name: 'Venice', weight: 2 },
    { id: 55, name: 'Zion', weight: 2 },
    { id: 56, name: 'Sicily', weight: 2 },
    { id: 57, name: 'Lol', weight: 2 },
    { id: 58, name: 'Naruto', weight: 2 },
    { id: 59, name: 'Luffy', weight: 2 },
    { id: 60, name: 'Monaco', weight: 2 },
    { id: 61, name: 'Shinobi', weight: 2 },
    { id: 62, name: 'Ninja', weight: 2 },
    { id: 63, name: 'Kill', weight: 2 },
    { id: 64, name: 'Dead', weight: 2 },
    { id: 65, name: 'Law', weight: 2 },
    { id: 66, name: 'Hawaii', weight: 2 },
    { id: 67, name: 'Bro', weight: 2 },
  ],
  mouth: [
    { id: 0, name: 'Sherlock', weight: 0 },
    { id: 1, name: 'Gurgaon', weight: 0 },
    { id: 2, name: '420', weight: 0 },
    { id: 3, name: 'Bleb', weight: 0 },
    { id: 4, name: 'Vape', weight: 0 },
    { id: 5, name: 'Cigar', weight: 0 },
    { id: 6, name: 'Tobacco', weight: 0 },
    { id: 7, name: 'NYC', weight: 0 },
    { id: 8, name: 'Party', weight: 0 },
    { id: 9, name: 'Mexico', weight: 0 },
    { id: 10, name: 'Seville', weight: 0 },
    { id: 11, name: 'Pizza', weight: 0 },
    { id: 12, name: 'Lollypop', weight: 0 },
    { id: 13, name: 'Smirk', weight: 0 },
    { id: 14, name: 'Smile', weight: 0 },
    { id: 15, name: 'Wow', weight: 0 },
    { id: 16, name: 'Love', weight: 0 },
    { id: 17, name: 'Lol', weight: 0 },
  ],
  beard: [
    { id: -1, name: null, weight: 20 },
    { id: 0, name: 'Washington', weight: 8 },
    { id: 1, name: 'Austin', weight: 8 },
    { id: 2, name: 'Tehran', weight: 8 },
    { id: 3, name: 'Hulk', weight: 8 },
    { id: 4, name: 'Lebanon', weight: 8 },
    { id: 5, name: 'Seedphrase', weight: 8 },
    { id: 6, name: 'Rhodes', weight: 8 },
    { id: 7, name: 'Moscow', weight: 8 },
    { id: 8, name: 'Dil Chahta Hai', weight: 8 },
    { id: 9, name: 'Muscat', weight: 8 },
  ],
  head: [
    { id: -1, name: null, weight: 20 },
    { id: 0, name: 'Minnesota', weight: 2 },
    { id: 1, name: 'Noogle', weight: 2 },
    { id: 2, name: 'Fireman', weight: 2 },
    { id: 3, name: 'Dictator', weight: 2 },
    { id: 4, name: 'Popeye', weight: 2 },
    { id: 5, name: 'Samurai', weight: 2 },
    { id: 6, name: 'Zorro', weight: 2 },
    { id: 8, name: 'King', weight: 2 },
    { id: 9, name: 'Guevara', weight: 2 },
    { id: 10, name: 'Dadosa', weight: 2 },
    { id: 11, name: 'Vegas', weight: 2 },
    { id: 12, name: 'Kazan', weight: 2 },
    { id: 13, name: 'NYC', weight: 2 },
    { id: 14, name: 'Oregon', weight: 2 },
    { id: 15, name: 'London', weight: 2 },
    { id: 16, name: 'Sparta', weight: 2 },
    { id: 17, name: 'Alabama', weight: 2 },
    { id: 18, name: 'Scotland', weight: 2 },
    { id: 19, name: 'Dream', weight: 2 },
    { id: 20, name: 'Bingham', weight: 2 },
    { id: 21, name: 'Pirate', weight: 2 },
    { id: 22, name: 'Mexico', weight: 2 },
    { id: 23, name: 'NJ', weight: 2 },
    { id: 24, name: 'Wizard', weight: 2 },
    { id: 25, name: 'Food', weight: 2 },
    { id: 26, name: 'Panama', weight: 2 },
    { id: 27, name: 'Cairo', weight: 2 },
    { id: 28, name: 'Monk', weight: 2 },
    { id: 29, name: 'Travolta', weight: 2 },
    { id: 30, name: 'Bravo', weight: 2 },
    { id: 31, name: 'Messi', weight: 2 },
    { id: 32, name: 'Sumo', weight: 2 },
    { id: 33, name: 'Military', weight: 2 },
    { id: 34, name: 'Rico', weight: 2 },
    { id: 35, name: 'Belair', weight: 2 },
    { id: 36, name: 'Punk', weight: 2 },
    { id: 37, name: 'Ride', weight: 2 },
    { id: 38, name: 'Ronin', weight: 2 },
    { id: 39, name: 'Pop', weight: 2 },
    { id: 40, name: 'Aantonop', weight: 2 },
    { id: 41, name: 'Music', weight: 2 },
    { id: 42, name: 'AirPods', weight: 2 },
    { id: 43, name: 'Angel', weight: 2 },
    { id: 44, name: 'Hell', weight: 2 },
    { id: 45, name: 'Altman', weight: 2 },
    { id: 46, name: 'Rastafari', weight: 2 },
    { id: 47, name: 'Ace Ventura', weight: 2 },
    { id: 48, name: 'Lenon', weight: 2 },
  ],
  eyes: [
    { id: 0, name: 'Angry', weight: 0 },
    { id: 1, name: 'Happy', weight: 0 },
    { id: 2, name: 'Sic', weight: 0 },
    { id: 3, name: 'Dead', weight: 0 },
    { id: 4, name: 'Hypnotised', weight: 0 },
    { id: 7, name: 'Love', weight: 0 },
    { id: 8, name: 'Sus', weight: 0 },
    { id: 9, name: 'Wut', weight: 0 },
    { id: 10, name: 'Gotcha', weight: 0 },
  ],
};
