import {
  AccountTree,
  Assignment,
  AttachMoney,
  Bed,
  BookOnline,
  BuildRounded,
  Business,
  CalendarMonth,
  CardGiftcard,
  Category,
  Chat,
  Computer,
  CurrencyExchange,
  Dashboard,
  DataArray,
  Description,
  Event,
  EventAvailable,
  Explore,
  Extension,
  Favorite,
  Flight,
  GroupAdd,
  Home,
  Hotel,
  Image,
  Info,
  Input,
  Label,
  List,
  LocalOffer,
  LocationCity,
  Lock,
  Mail,
  ManageAccounts,
  Map,
  Menu,
  More,
  People,
  Person,
  Policy,
  Public,
  RateReview,
  Scale,
  Schedule,
  Stars,
  Storage,
  Storefront,
  Task,
  Token,
  TrendingUp,
  Upload,
} from "@mui/icons-material";

interface NavigationLink {
  id: string;
  title: string;
  list: {
    id: string;
    name: string;
    link: string;
    iconName: React.ElementType;
  }[];
}

export const navigationLinks: NavigationLink[] = [
  {
    id: "",
    title: "Zo Console",
    list: [
      {
        id: "home",
        name: "Home",
        link: "/",
        iconName: Menu,
      },
      {
        id: "houses",
        name: "Zo Houses",
        link: "/houses",
        iconName: Home,
      },
      {
        id: "availability-view",
        name: "Availability View",
        link: "/availability-view",
        iconName: Hotel,
      },
      {
        id: "visitors",
        name: "Visitors",
        link: "/visitors",
        iconName: People,
      },
      {
        id: "bookings",
        name: "Bookings",
        link: "/bookings",
        iconName: Bed,
      },
      {
        id: "playlists",
        name: "Playlists",
        link: "/playlists",
        iconName: Computer,
      },
      {
        id: "showcase",
        name: "Showcase",
        link: "/showcase",
        iconName: Storefront,
      },
    ],
  },
  {
    id: "xostel",
    title: "Xostel",
    list: [
      {
        id: "partner",
        name: "Partners",
        link: "/partners",
        iconName: Business,
      },
      {
        id: "partner-availability-calendar",
        name: "Availability Calendar",
        link: "/partner-availability-calendar",
        iconName: CalendarMonth,
      },
    ],
  },
  {
    id: "zo-trips",
    title: "Zo Trips",
    list: [
      {
        id: "trips",
        name: "Trip",
        link: "/trips",
        iconName: Explore,
      },
      {
        id: "trip-bookings",
        name: "Trip Booking",
        link: "/trip-bookings",
        iconName: EventAvailable,
      },
      {
        id: "trip-tools",
        name: "Trip Tools",
        link: "/trip-tools",
        iconName: BuildRounded,
      },
      {
        id: "trip-vendors",
        name: "Trip Vendors",
        link: "/trip-vendors",
        iconName: Storefront,
      },
    ],
  },

  {
    id: "house-operations",
    title: "House Operations",
    list: [
      {
        id: "attendance",
        name: "Attendance",
        link: "/house-ops/attendance",
        iconName: GroupAdd,
      },
      {
        id: "schedules",
        name: "Schedules",
        link: "/house-ops/schedules",
        iconName: Schedule,
      },
      {
        id: "tasks",
        name: "Tasks",
        link: "/house-ops/tasks",
        iconName: Task,
      },
      {
        id: "templates",
        name: "Templates",
        link: "/house-ops/templates",
        iconName: Assignment,
      },
    ],
  },
  {
    id: "community",
    title: "Community",
    list: [
      {
        id: "events",
        name: "Events",
        link: "/events",
        iconName: Event,
      },
      {
        id: "activity-manager",
        name: "Activity Manager",
        link: "/activity-manager",
        iconName: Event,
      },
      {
        id: "bulletin",
        name: "Bulletin Boards",
        link: "/bulletin-boards",
        iconName: Dashboard,
      },
      {
        id: "zostel-home",
        name: "Zostel Home",
        link: "/zostel-home",
        iconName: Computer,
      },
      {
        id: "poa",
        name: "POAs",
        link: "/poa",
        iconName: CardGiftcard,
      },
      {
        id: "vibe-curator",
        name: "Vibe Curator",
        link: "/vibe-curator",
        iconName: Stars,
      },
    ],
  },
  {
    id: "general",
    title: "General",
    list: [
      {
        id: "founders",
        name: "Founders",
        link: "/founders",
        iconName: Favorite,
      },
      {
        id: "users",
        name: "Users",
        link: "/users",
        iconName: Person,
      },
      {
        id: "destinations",
        name: "Destinations",
        link: "/destinations",
        iconName: LocationCity,
      },
      //   {
      //     id: "misc",
      //     name: "Miscellaneous",
      //     link: "/misc",
      //     iconName: More,
      //   },
      {
        id: "maps",
        name: "Maps",
        link: "/maps",
        iconName: Map,
      },
    ],
  },
  {
    id: "admin",
    title: "Admin",
    list: [
      {
        id: "chats",
        name: "Chats & Access",
        link: "/threads",
        iconName: Chat,
      },
      {
        id: "roles",
        name: "User Roles",
        link: "/user-roles",
        iconName: ManageAccounts,
      },
    ],
  },
  {
    id: "miscellaneous",
    title: "Miscellaneous",
    list: [
      {
        id: "allowlist",
        name: "AllowList",
        link: "/misc/allowlist",
        iconName: List,
      },
      {
        id: "cancellation-policy",
        name: "Cancellation Policy",
        link: "/misc/cancellation-policy",
        iconName: Policy,
      },
      {
        id: "cost-heads",
        name: "Cost Heads",
        link: "/misc/cost-heads",
        iconName: AttachMoney,
      },
      {
        id: "country",
        name: "Country",
        link: "/misc/country",
        iconName: Public,
      },
      {
        id: "coupons",
        name: "Coupons",
        link: "/misc/coupons",
        iconName: LocalOffer,
      },
      {
        id: "cultures",
        name: "Cultures",
        link: "/misc/cultures",
        iconName: People,
      },
      {
        id: "currency",
        name: "Currency",
        link: "/misc/currency",
        iconName: AttachMoney,
      },
      {
        id: "data-fields",
        name: "Data Fields",
        link: "/misc/data-fields",
        iconName: DataArray,
      },
      {
        id: "database",
        name: "Database",
        link: "/misc/database",
        iconName: Storage,
      },
      {
        id: "discover-card",
        name: "Discover Card",
        link: "/misc/discover-card",
        iconName: CardGiftcard,
      },
      {
        id: "entry-points",
        name: "Entry Points",
        link: "/misc/entry-points",
        iconName: Input,
      },
      {
        id: "event-scraper",
        name: "Event Scraper",
        link: "/misc/event-scraper",
        iconName: Event,
      },
      {
        id: "features",
        name: "Features",
        link: "/misc/features",
        iconName: Extension,
      },
      {
        id: "invitations",
        name: "Invitations",
        link: "/misc/invitations",
        iconName: Mail,
      },
      {
        id: "leads",
        name: "Leads",
        link: "/misc/leads",
        iconName: TrendingUp,
      },
      {
        id: "locks",
        name: "Locks",
        link: "/misc/locks",
        iconName: Lock,
      },
      {
        id: "media-upload",
        name: "Media Upload",
        link: "/misc/media-upload",
        iconName: Upload,
      },
      {
        id: "memes",
        name: "Memes",
        link: "/misc/memes",
        iconName: Image,
      },
      {
        id: "metadata",
        name: "Metadata",
        link: "/misc/metadata",
        iconName: Info,
      },
      {
        id: "nodes",
        name: "Nodes",
        link: "/misc/nodes",
        iconName: AccountTree,
      },
      {
        id: "offers",
        name: "Offers",
        link: "/misc/offers",
        iconName: LocalOffer,
      },
      {
        id: "rates-manager",
        name: "Rates Manager",
        link: "/misc/rates-manager",
        iconName: CurrencyExchange,
      },
      {
        id: "review-categories",
        name: "Review Categories",
        link: "/misc/review-categories",
        iconName: Category,
      },
      {
        id: "reviews",
        name: "Reviews",
        link: "/misc/reviews",
        iconName: RateReview,
      },
      {
        id: "tags",
        name: "Tags",
        link: "/misc/tags",
        iconName: Label,
      },
      {
        id: "templates",
        name: "Templates",
        link: "/misc/templates",
        iconName: Description,
      },
      {
        id: "token-airdrops",
        name: "Token Airdrop",
        link: "/misc/token-airdrops",
        iconName: Token,
      },
      {
        id: "token-grant",
        name: "Token Grant",
        link: "/misc/token-grant",
        iconName: Token,
      },
      {
        id: "vendors",
        name: "Vendors",
        link: "/misc/vendors",
        iconName: Storefront,
      },
      {
        id: "weights",
        name: "Weights",
        link: "/misc/weights",
        iconName: Scale,
      },
      {
        id: "zo-points",
        name: "Zo Points",
        link: "/misc/zo-points",
        iconName: Stars,
      },
    ],
  },
];
